---
apiVersion: v1
kind: Service
metadata:
  name: cloudshell
  namespace: openwhisk
  labels:
    name: cloudshell
spec:
  type: NodePort
  selector:
    name: cloudshell
  ports:
    - port: 8080
      targetPort: 8080
      name: http

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudshell
  namespace: openwhisk
  labels:
    name: cloudshell
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cloudshell
    spec:
      restartPolicy: Always
      volumes:
      - name: logs
        emptyDir: {}
      containers:
      - name: cloudshell
        imagePullPolicy: Always
        image: nao16t/cloudshell
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: "AUTH"
          value: "23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
        volumeMounts:
          - name: logs
            mountPath: "/logs"
