version: 2
jobs:
  build:
    docker:
      - image: nao16t/swipl8jpl-kafka
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: setting up
          command: |
            echo "$GCP_APP_CRED" > /root/credential.json
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            make build_image
            make app_image
      - run:
          name: test with kafka
          command: make test_with_kafka -e FAASSHELL_MQ=kafka -e FAASSHELL_APIHOST=http://127.0.0.1:8080
      - run:
          name: deploy
          command: |
            pushd /root/project/heroku
            heroku container:login
            heroku container:push web --app protected-depths-49487
            heroku container:release web --app protected-depths-49487
            popd
      - run:
          name: unit test
          command: make unit_test
      - run:
          name: functional test
          command: make functional_test
