version: 2
jobs:
  build:
    docker:
      - image: nao16t/swipl7jpl
    steps:
      - checkout
      - run:
          name: create /logs for testing
          command: mkdir /logs
      - run:
          name: unit test
          command: make unit_test
      - run:
          name: functional test
          command: make functional_test
      - run:
          name: Print the Current Time
          command: date
