version: 2
jobs:
  build:
    docker:
      - image: swipl:7.5.15
    steps:
      - checkout
      - run:
          name: install tools
          command: apt-get update && apt-get install -y make procps
      - run:
          name: create /logs for testing
          command: mkdir /logs
      - run:
          name: unit test
          command: make unit_test
      - run:
          name: functional test
          command: make functional_test
      - run:
          name: Print the Current Time
          command: date
