version: 2
jobs:
  build:
    docker:
      - image: swipl:7.5.15
    steps:
      - checkout
      - run:
          name: install make
          command: apt-get update && apt-get install -y make
      - run:
          name: unit test
          command: make unit_test
      - run:
          name: Print the Current Time
          command: date
