#!/usr/bin/expect
# Copyright 2018 FUJITSU LIMITED
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

# set timeout 10

proc report {result} {
    global case
    puts "\n\n-> $result : $case\n"
}

spawn -noecho src/faasshell_repl.pl

expect_after {
    # default timetout is 10 sec
    timeout {
        report {timeout exit(1)}
        # send Ctl-D twice
        send "\004"
        expect "faasshell debug>"
        send "\004"
        wait
        close
        exit 1
    }
}

set case "start repl"
expect "faasshell>" { report {passed} }

#
# basic operations
#
set case "set a global variable 'x'"
send "set(x,1).\r"
expect -re {Output=_(\d)+} { report {passed} }

set case "check the global variable 'x'"
send "getall.\r"
expect -re {Output=_(\d)+\{x:1\}} { report {passed} }

set case "set a global variable 'X'"
send "set(X,2).\r"
expect "ERROR:*" { report {passed} }

set case "check if the global variable 'x' is kept"
send "getall.\r"
expect -re {Output=_(\d)+\{x:1\}}  { report {passed} }

set case "set a global variable 'y'"
send "set(y,2).\r"
expect -re {Output=_(\d)+} { report {passed} }

set case "check if the global variable 'x' and 'y'"
send "getall.\r"
expect -re {Output=_(\d)+\{x:1,y:2\}}  { report {passed} }

set case "set a global variable 'z'"
send "set(z,3).\r"
expect -re {Output=_(\d)+} { report {passed} }

set case "check if the global variable 'x', 'y' and 'z'"
send "getall.\r"
expect -re {Output=_(\d)+\{x:1,y:2,z:3\}}  { report {passed} }

set case "unset the global variable 'z'"
send "unset(z).\r"
expect -re {Output=_(\d)+} { report {passed} }

set case "check if the global variable 'x' and 'y' are kept"
send "getall.\r"
expect -re {Output=_(\d)+\{x:1,y:2\}}  { report {passed} }

set case "unset the global variable 'x' and 'y'"
send "unset(x), unset(y).\r"
expect -re {Output=_(\d)+} { report {passed} }

set case "check if the global variable is empty"
send "getall.\r"
expect -re {Output=_(\d)+\{\}}  { report {passed} }

set case "unset unknown global variable 'unknown'"
send "set(x,1), unset(unknown).\r"
expect -re {Output=_(\d)+} { report {passed} }

set case "check if the global variable 'x' is set"
send "getall.\r"
expect -re {Output=_(\d)+\{x:1\}}  { report {passed} }

set case "unsetall global variable"
send "set(x,1), set(y,2), set(z,3), unsetall, getall.\r"
expect -re {Output=_(\d)+}  { report {passed} }

set case "call getall in the middle of the workflow"
send "startsm(1),getall.\r"
expect -re {Warning: dropped workflow data '1'}  { report {passed} }

set case "call startsm in the middle of the workflow"
send "startsm(1),startsm(2).\r"
expect -re {Warning: dropped workflow data '1'}  { report {passed} }

set case "set a value to local variable"
send "X = 1, startsm(X).\r"
expect {
    {Output=1} { exp_continue }
    {X=1}  { report {passed} }
}

set case "\$x to get the value of the global variable 'x'"
send "set(x,1), X = \$x, startsm(X).\r"
expect {
    {Output=1} { exp_continue }
    {X=1}  { report {passed} }
}

set case "#lambda to eval the value of the global variable 'lambda'"
send "set(lambda, set(x,1)), #lambda, X = \$x, startsm(X).\r"
expect {
    {Output=1} { exp_continue }
    {X=1}  { report {passed} }
}

set case "create a block of states by parentheses"
send "set(lambda, set(x,1)), { #lambda, X = \$x }, startsm(X).\r"
expect {
    {Output=1} { exp_continue }
    {X=1}  { report {passed} }
}

#
# run samples/wsk/dsl/job_status_poller.dsl using global variables
#
set case "unsetall global variable before running job_status_poller.dsl"
send "unsetall.\r"
expect -re {Output=_(\d)+}  { report {passed} }

set case "register task('Submit Job')"
send "set(submit_job, task('Submit Job', \
\"frn:wsk:functions:::function:/whisk.system/utils/echo\", \
\[result_path('$.guid')\])),\r"
expect "|" { report {passed} }

set case "register wait('Wait X Seconds')"
send "set(wait_x_secs, wait('Wait X Seconds',seconds_path('$.wait_time'),\[\])),\r"
expect "|" { report {passed} }

set case "register wait('Wait X Seconds')"
send "set(get_job_status, \
task('Get Job Status',\"frn:wsk:functions:::function:job\", \
\[input_path('$.guid'),result_path('$.guid')\])),\r"
expect "|" { report {passed} }

set case "register fail('Job Failed')"
send "set(job_failed, fail('Job Failed',\[error(\"DescribeJob returned FAILED\"), \
cause(\"AWS Batch Job Failed\")\])),\r"
expect "|" { report {passed} }

set case "register fail('Get Final Job Status')"
send "set(get_final_job_status, task('Get Final Job Status', \
\"frn:wsk:functions:::function:hello\",\[\])),\r"
expect "|" { report {passed} }

set case "register choices('Job Complete?')"
send "set(job_complete, \
choices('Job Complete?', \
\[ \
   case(string_equals('$.guid.status',\"FAILED\"), \[#job_failed]), \
   case(string_equals('$.guid.status',\"SUCCEEDED\"), \[#get_final_job_status]) \
\],
\[ \
   default(\[goto(state(#wait_x_secs))\]) \
\])),\r"
expect "|" { report {passed} }

set case "run job_status_poller.dsl for succeeded case"
send "startsm(_{wait_time:1, \
                params:\[\"DEFAULT\", \"SUCCEEDED\"\], \
                name:\"Poller\"}), \
#submit_job, #wait_x_secs, #get_job_status, #job_complete.\r"
expect -timeout 20 -re {Output=_(\d)+\{payload:Hello, Poller!\}} { report {passed} }

set case "run job_status_poller.dsl for failed case"
send "startsm(_{wait_time:1, \
                params:\[\"DEFAULT\", \"FAILED\"\], \
                name:\"Poller\"}), \
#submit_job, #wait_x_secs, #get_job_status, #job_complete.\r"
expect -timeout 20 -re \
{Output=_(\d)+\{cause:AWS Batch Job Failed,error:DescribeJob returned FAILED\}} \
{ report {passed} }

# send Ctl-D twice
sleep 1.0
set case "exit repl"
send "\004"
expect "faasshell debug>" { report {passed} }
send "\004"
wait
close
exit 0
