#!/usr/bin/expect
# Copyright 2018 FUJITSU LIMITED
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

spawn src/faasshell_repl.pl
expect "faasshell>"

send "set(x,1).\n"
expect -re "Output=_\[0-9]+"

send "getall.\r"
expect { -re Output=_[0-9]+\{x:1\} }

send "set(X,2).\n"
expect "ERROR:"

send "getall.\n"
expect -re "Output=_(\d)+\{x:1\}"

close
exit
